Repository TheRealJackiBoi/dat2-fog-carport, pull requests merged in 2023-05, with the labels that each got.

#28 Pagetemplate
  src/main/java/dat/backend/model/persistence/ConnectionPool.java
  src/main/resources/fog-startcode.sql
  src/main/resources/startcode.sql
  src/main/webapp/WEB-INF/tags/pagetemplate.tag
  src/main/webapp/css/style.css
  src/main/webapp/images/Fog_logo.svg
  src/main/webapp/images/carport.jpg
  src/main/webapp/index.jsp
  src/test/java/dat/backend/persistence/UserMapperTest.java
Labels: enhancement

#63 Customer see orders
  src/main/java/dat/backend/control/CreateOrder.java
  src/main/java/dat/backend/control/CustomerSeeOrder.java
  src/main/java/dat/backend/control/Login.java
  src/main/java/dat/backend/control/SignUp.java
  src/main/java/dat/backend/model/persistence/UserFacade.java
  src/main/java/dat/backend/model/persistence/UserMapper.java
  src/main/webapp/WEB-INF/customer_see_orders.jsp
  src/main/webapp/WEB-INF/tags/pagetemplate.tag
  src/main/webapp/WEB-INF/welcome.jsp
  src/main/webapp/error.jsp
  src/main/webapp/index.jsp
  src/main/webapp/login.jsp
  src/main/webapp/signup.jsp
  src/test/java/dat/backend/persistence/UserMapperTest.java
Labels: enhancement

#50 removed old comment, removed redundant code, added new comments
  src/main/java/dat/backend/control/CreateOrder.java
Labels: enhancement

#74 Create order
  src/main/java/dat/backend/control/CancelOrder.java
  src/main/java/dat/backend/control/CreateOrder.java
  src/main/java/dat/backend/model/entities/LinkItemListMaterialVariants.java
  src/main/java/dat/backend/model/persistence/LinkItemListMaterialsVariantsFacade.java
  src/main/java/dat/backend/model/persistence/LinkItemListMaterialsVariantsMapper.java
  src/main/java/dat/backend/model/persistence/OrdersFacade.java
  src/main/java/dat/backend/model/persistence/OrdersMapper.java
  src/main/java/dat/backend/model/persistence/UserMapper.java
  src/main/resources/fog-startcode.sql
  src/main/webapp/WEB-INF/ordering.jsp
  src/main/webapp/WEB-INF/tags/pagetemplate.tag
  src/main/webapp/images/Fog_logo.ico
Labels: enhancement

#70 Link item list material variants
  src/main/java/dat/backend/model/persistence/ItemListFacade.java
  src/main/java/dat/backend/model/persistence/ItemListMapper.java
  src/main/java/dat/backend/model/persistence/LinkItemListMaterialsVariantsFacade.java
  src/main/java/dat/backend/model/persistence/LinkItemListMaterialsVariantsMapper.java
Labels: enhancement

#79 customer_see_orders working, missing orderconfirm route
  src/main/java/dat/backend/control/EditUser.java
  src/main/webapp/WEB-INF/customer_see_orders.jsp
Labels: enhancement

#87 working see order for customers
  src/main/java/dat/backend/control/CreateOrder.java
  src/main/java/dat/backend/control/SeeOrder.java
  src/main/webapp/WEB-INF/customer_see_orders.jsp
  src/main/webapp/WEB-INF/view_order.jsp
  src/main/webapp/css/style.css
Labels: enhancement

#98 added logik to partscalculator, added max and min to ordering jsp,
  src/main/java/dat/backend/model/services/ItemListPopulator.java
  src/main/java/dat/backend/model/services/PartsCalculator.java
  src/main/webapp/WEB-INF/ordering.jsp
Labels: enhancement

#103 Dev
  src/main/java/dat/backend/control/AdminChangeCostPrices.java
  src/main/java/dat/backend/control/AdminChangeSalesPrice.java
  src/main/java/dat/backend/control/AdminEditUsers.java
  src/main/java/dat/backend/control/AdminSeePartList.java
  src/main/java/dat/backend/control/AdminViewOrders.java
  src/main/java/dat/backend/control/CreateOrder.java
  src/main/java/dat/backend/control/EditUser.java
  src/main/java/dat/backend/control/SeeOrder.java
  src/main/java/dat/backend/control/SignUp.java
  src/main/java/dat/backend/model/entities/Order.java
  src/main/java/dat/backend/model/persistence/ItemListFacade.java
  src/main/java/dat/backend/model/persistence/ItemListMapper.java
  src/main/java/dat/backend/model/persistence/LinkItemListMaterialsVariantsFacade.java
  src/main/java/dat/backend/model/persistence/LinkItemListMaterialsVariantsMapper.java
  src/main/java/dat/backend/model/persistence/MaterialsFacade.java
  src/main/java/dat/backend/model/persistence/MaterialsMapper.java
  src/main/java/dat/backend/model/persistence/OrdersFacade.java
  src/main/java/dat/backend/model/persistence/OrdersMapper.java
  src/main/java/dat/backend/model/persistence/PartsFacade.java
  src/main/java/dat/backend/model/persistence/PartsMapper.java
  src/main/java/dat/backend/model/persistence/RoleFacade.java
  src/main/java/dat/backend/model/persistence/RoleMapper.java
  src/main/java/dat/backend/model/persistence/UserFacade.java
  src/main/java/dat/backend/model/persistence/UserMapper.java
  src/main/java/dat/backend/model/services/ItemListPopulator.java
  src/main/java/dat/backend/model/services/PartsCalculator.java
  src/main/webapp/WEB-INF/admin-view-orders.jsp
  src/main/webapp/WEB-INF/admin_change_costprices.jsp
  src/main/webapp/WEB-INF/admin_edit_users.jsp
  src/main/webapp/WEB-INF/admin_see_partslist.jsp
  src/main/webapp/WEB-INF/customer_see_orders.jsp
  src/main/webapp/WEB-INF/edituserinfo.jsp
  src/main/webapp/WEB-INF/ordering.jsp
  src/main/webapp/WEB-INF/sales_change_salesprice.jsp
  src/main/webapp/WEB-INF/tags/pagetemplate.tag
  src/main/webapp/WEB-INF/view_order.jsp
  src/main/webapp/WEB-INF/welcome.jsp
  src/main/webapp/css/style.css
  src/main/webapp/index.jsp
  src/main/webapp/javascript/MatchChecker.js
  src/main/webapp/signup.jsp
  src/test/java/dat/backend/model/persistence/MaterialsMapperTest.java
Labels: enhancement

#110 update
  src/main/java/dat/backend/model/persistence/OrdersMapper.java
  src/main/resources/fog-startcode.sql
  src/main/webapp/WEB-INF/admin_edit_users.jsp
  src/main/webapp/WEB-INF/tags/pagetemplate.tag
  src/main/webapp/css/style.css
  src/main/webapp/index.jsp
Labels: bug, enhancement

#118 Able to see partslist
  src/main/java/dat/backend/control/AdminSeePartList.java
  src/main/webapp/WEB-INF/view_order.jsp
Labels: enhancement

#123 JavaDoc created🤓
  pom.xml
  src/main/java/dat/backend/control/AdminChangeCostPrices.java
  src/main/java/dat/backend/control/AdminChangeSalesPrice.java
  src/main/java/dat/backend/control/AdminChangeStatus.java
  src/main/java/dat/backend/control/AdminEditUsers.java
  src/main/java/dat/backend/control/AdminSeePartList.java
  src/main/java/dat/backend/control/AdminViewOrders.java
  src/main/java/dat/backend/control/CancelOrder.java
  src/main/java/dat/backend/control/CreateOrder.java
  src/main/java/dat/backend/control/CustomerSeeOrder.java
  src/main/java/dat/backend/control/EditUser.java
  src/main/java/dat/backend/control/Login.java
  src/main/java/dat/backend/control/Logout.java
  src/main/java/dat/backend/control/SeeOrder.java
  src/main/java/dat/backend/control/SignUp.java
  src/main/java/dat/backend/control/SvgServlet.java
  src/main/java/dat/backend/control/package-info.java
  src/main/java/dat/backend/model/config/ApplicationStart.java
  src/main/java/dat/backend/model/entities/ItemList.java
  src/main/java/dat/backend/model/entities/LinkItemListMaterialVariants.java
  src/main/java/dat/backend/model/entities/MaterialVariants.java
  src/main/java/dat/backend/model/entities/Materials.java
  src/main/java/dat/backend/model/entities/Order.java
  src/main/java/dat/backend/model/entities/Part.java
  src/main/java/dat/backend/model/entities/Role.java
  src/main/java/dat/backend/model/entities/Status.java
  src/main/java/dat/backend/model/entities/Type.java
  src/main/java/dat/backend/model/entities/Unit.java
  src/main/java/dat/backend/model/entities/User.java
  src/main/java/dat/backend/model/exceptions/DatabaseException.java
  src/main/java/dat/backend/model/package-info.java
  src/main/java/dat/backend/model/persistence/ItemListFacade.java
  src/main/java/dat/backend/model/persistence/MaterialVariantsMapper.java
  src/main/java/dat/backend/model/persistence/OrdersFacade.java
  src/main/java/dat/backend/model/persistence/OrdersMapper.java
  src/main/java/dat/backend/model/persistence/RoleFacade.java
  src/main/java/dat/backend/model/services/Authentication.java
  src/main/java/dat/backend/model/services/CarportSVG.java
  src/main/java/dat/backend/model/services/ItemListPopulator.java
  src/main/java/dat/backend/model/services/PartsCalculator.java
  src/main/java/dat/backend/model/services/SVG.java
Labels: documentation
